version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: payments-postgres
    environment:
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: payments
      POSTGRES_DB: paymentsdb
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: payments-redis
    ports:
      - "6379:6379"